/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Movie_database;

import com.placeholder.PlaceHolder;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabrian
 */
public class dlgEditMovie extends javax.swing.JDialog {

    /**
     * @return the judul
     */
    public String getJudul() {
        return judul;
    }

    /**
     * @param judul the judul to set
     */
    public void setJudul(String judul) {
        this.judul = judul;
    }

    /**
     * @return the pengarang
     */
    public String getSutradara() {
        return sutradara;
    }

    /**
     * @param sutradara the pengarang to set
     */
    public void setSutradara(String sutradara) {
        this.sutradara = sutradara;
    }
    private ArrayList<JComboBox> cbGenres = new ArrayList<>();
    private String judul = null;
    private String sutradara = null;

    /** Creates new form dlgEditBuku */
    public dlgEditMovie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblCover = new javax.swing.JLabel();
        btnPilihSampulBuku = new javax.swing.JButton();
        fldJudul = new javax.swing.JTextField();
        fldSutradara = new javax.swing.JTextField();
        fldStudio = new javax.swing.JTextField();
        fldTahunrelease = new javax.swing.JTextField();
        lblPeringkat = new javax.swing.JLabel();
        spiPeringkat = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        fdaSinopsis = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();
        rbSudah = new javax.swing.JRadioButton();
        rbBelum = new javax.swing.JRadioButton();
        cbGenre1 = new javax.swing.JComboBox<>();
        cbGenre2 = new javax.swing.JComboBox<>();
        cbGenre3 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Edit Buku");

        lblCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCover.setName(""); // NOI18N

        btnPilihSampulBuku.setText("Pilih Sampul Buku");
        btnPilihSampulBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPilihSampulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihSampulBukuActionPerformed(evt);
            }
        });

        fldJudul.setEditable(false);

        fldSutradara.setEditable(false);

        lblPeringkat.setText("Peringkat");

        spiPeringkat.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        fdaSinopsis.setColumns(20);
        fdaSinopsis.setLineWrap(true);
        fdaSinopsis.setRows(5);
        fdaSinopsis.setWrapStyleWord(true);
        jScrollPane1.setViewportView(fdaSinopsis);

        lblStatus.setText("sudah tonton?");

        rbSudah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbSudah.setForeground(new java.awt.Color(0, 255, 0));
        rbSudah.setText("Sudah");
        rbSudah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbSudah.setPreferredSize(new java.awt.Dimension(60, 23));

        rbBelum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbBelum.setForeground(new java.awt.Color(255, 0, 0));
        rbBelum.setText("Belum");
        rbBelum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbGenre1.setModel(new DefaultComboBoxModel(DatabaseUtil.selectSemuaGenre().toArray()));

        cbGenre2.setModel(new DefaultComboBoxModel(DatabaseUtil.selectSemuaGenre().toArray()));

        cbGenre3.setModel(new DefaultComboBoxModel(DatabaseUtil.selectSemuaGenre().toArray()));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("judul :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("genre :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("sutradara:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("studio :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("tahun release :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("sinopsis:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnSimpan)
                        .addGap(54, 54, 54)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCover, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 367, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(fldJudul, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fldSutradara, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbGenre1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbGenre2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbGenre3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPilihSampulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblPeringkat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spiPeringkat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbSudah, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbBelum)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fldTahunrelease, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fldStudio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(346, 346, 346)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbGenre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGenre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGenre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fldSutradara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCover, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldTahunrelease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnPilihSampulBuku))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSudah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbBelum))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spiPeringkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPeringkat))
                        .addGap(14, 14, 14))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        BufferedImage cover = null;
        try{
            cover = ImageIO.read(new File("images/buku/defaultImage.jpg"));
            BufferedImage scaledCover = Scalr.resize(cover,147);

            ImageIcon coverIcon = new ImageIcon(scaledCover);
            lblCover.setIcon(coverIcon);
        }
        catch(IOException e){
            System.out.println(e.getMessage());
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final ButtonGroup grpStatus = new ButtonGroup();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.getRootPane().setDefaultButton(btnSimpan);
        
        //grouping rb
        grpStatus.add(rbBelum);
      
        grpStatus.add(rbSudah);
        
        //Listing cbGenre
        cbGenres.add(cbGenre1);
        cbGenres.add(cbGenre2);
        cbGenres.add(cbGenre3);
        
        //isi kolom2
        Movie movie = DatabaseUtil.selectMovie(judul, sutradara);
        //cbGenre
        ArrayList<String> genres = movie.getGenres();
        int i = 0;
        for(JComboBox cbGenre : cbGenres){
            cbGenre.addItem("Genre");
            if(i < genres.size()) cbGenre.setSelectedItem(genres.get(i));
            else cbGenre.setSelectedItem("Genre");
            i++;
        }
        
        //rbStatus
        switch(movie.getTranslatedStatus()){
            
            case "Sudah": rbSudah.setSelected(true); break;
            case "Belum": 
            default: rbBelum.setSelected(true); break;
        }
        
        //field dan spinner
        fldJudul.setText(judul);
        fldSutradara.setText(sutradara);
        fldStudio.setText(movie.getStudio());
        spiPeringkat.setValue(movie.getPeringkat());
        fldTahunrelease.setText(Integer.toString(movie.getTahunrelease()));
        fdaSinopsis.setText(movie.getSinopsis());
        
        //gambar
        if(!"defaultImage.jpg".equals(movie.getPathSampul())){
            BufferedImage coverImage = null;
            try{
                coverImage = ImageIO.read(new File("images/movie/" + movie.getPathSampul()));
                BufferedImage scaledCoverImage = Scalr.resize(coverImage,147);

                ImageIcon coverIcon = new ImageIcon(scaledCoverImage);
                lblCover.setIcon(coverIcon);
            }
            catch(IOException e){
                System.out.println(e.getMessage());
            }
        }
        pathSampul = movie.getPathSampul();
        fileCover = new File(pathSampul);
        
        
        new PlaceHolder(fldSutradara,"Sutradara");
        new PlaceHolder(fldTahunrelease,"Tahun release");
        new PlaceHolder(fdaSinopsis,"Sinopsis . . .");
    }//GEN-LAST:event_formWindowOpened

    private File fileCover = null;
    private String pathSampul = "";
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        //insert
        String studio = fldStudio.getText();
        int peringkat = (int) spiPeringkat.getValue();
        String sinopsis = fdaSinopsis.getText();
        String status;
        if(rbSudah.isSelected()) status = "2";
       
        else status = "0";

        if(fileCover != null){
            String fileName = fldJudul.getText() + "-" +
                    fldSutradara.getText() + "." +
                    ExtensionUtil.getExtension(fileCover);
            Path target = Paths.get("images/movie/" + fileName);
            try {
                Files.copy(fileCover.toPath(), target, StandardCopyOption.REPLACE_EXISTING);
                
                pathSampul = fileName;
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }
        
        ArrayList<String> genres = new ArrayList<>();
        for(JComboBox cbGenre: cbGenres){
            if(!cbGenre.getSelectedItem().equals("Genre") && 
                    !genres.contains((String) cbGenre.getSelectedItem())){
                genres.add((String) cbGenre.getSelectedItem());
            }
        }
        int tahunTerbit = 0;
        boolean isSuccess = false;

        try{
            if(!"Tahun release".equals(fldTahunrelease.getText())) tahunTerbit = 
                    Integer.parseInt(fldTahunrelease.getText());
            
            if(!judul.equals("Judul") && !sutradara.equals("Sutradara")){
                isSuccess = DatabaseUtil.editMovie(judul, sutradara, studio, genres, peringkat, 
                    tahunTerbit, sinopsis, status, pathSampul);
            
                if(isSuccess){
                    JOptionPane.showMessageDialog(this, 
                                        "Perubahan Movie berhasil disimpan",
                                        "Perubahan Movie Disimpan",
                                        JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
                else{
                  
                    JOptionPane.showMessageDialog(this,
                                        "Perubahan Movie gagal disimpan",
                                        "Error: Movie Gagal Disimpan",
                                        JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
               
                JOptionPane.showMessageDialog(this,
                        "Judul dan Sutradara tidak boleh kosong atau diisi \"Judul\"  dan \"Sutradara\"",
                        "Error: Judul dan Sutradara Kosong",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException | HeadlessException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnPilihSampulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihSampulBukuActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.addChoosableFileFilter(new ImageFilter());
        jfc.setAcceptAllFileFilterUsed(false);
        
        int returnVal = jfc.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            
            try {
                BufferedImage image = ImageIO.read(file);
                
                BufferedImage scaledImage = Scalr.resize(image,147);
                ImageIcon coverIcon = new ImageIcon (scaledImage);
                lblCover.setIcon(coverIcon);
                
                fileCover = file;
                pathSampul = file.getAbsolutePath();
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        } else {
        }
    }//GEN-LAST:event_btnPilihSampulBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgEditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgEditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgEditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgEditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgEditMovie dialog = new dlgEditMovie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnPilihSampulBuku;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbGenre1;
    private javax.swing.JComboBox<String> cbGenre2;
    private javax.swing.JComboBox<String> cbGenre3;
    private javax.swing.JTextArea fdaSinopsis;
    private javax.swing.JTextField fldJudul;
    private javax.swing.JTextField fldStudio;
    private javax.swing.JTextField fldSutradara;
    private javax.swing.JTextField fldTahunrelease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCover;
    private javax.swing.JLabel lblPeringkat;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton rbBelum;
    private javax.swing.JRadioButton rbSudah;
    private javax.swing.JSpinner spiPeringkat;
    // End of variables declaration//GEN-END:variables

}
