/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movie_database;

import com.placeholder.PlaceHolder;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 
 * @author Fabrian
 */
public class dlgTambahMovie extends javax.swing.JDialog {
    
    
    private ArrayList<JComboBox> cbGenres = new ArrayList<>();
    /**
     * Creates new form dlgTambahBuku
     */
    public dlgTambahMovie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblCover = new javax.swing.JLabel();
        btnPilihSampulBuku = new javax.swing.JButton();
        fldJudul = new javax.swing.JTextField();
        fldSutradara = new javax.swing.JTextField();
        fldStudio = new javax.swing.JTextField();
        fldTahunrelease = new javax.swing.JTextField();
        lblPeringkat = new javax.swing.JLabel();
        spiPeringkat = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        fdaSinopsis = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();
        rbSudah = new javax.swing.JRadioButton();
        rbBelum = new javax.swing.JRadioButton();
        cbGenre1 = new javax.swing.JComboBox<>();
        cbGenre2 = new javax.swing.JComboBox<>();
        cbGenre3 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Movie");

        lblCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCover.setName(""); // NOI18N

        btnPilihSampulBuku.setText("Pilih cover");
        btnPilihSampulBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPilihSampulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihSampulBukuActionPerformed(evt);
            }
        });

        fldJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldJudulActionPerformed(evt);
            }
        });

        lblPeringkat.setText("Rating:");

        spiPeringkat.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        fdaSinopsis.setColumns(20);
        fdaSinopsis.setLineWrap(true);
        fdaSinopsis.setRows(5);
        fdaSinopsis.setWrapStyleWord(true);
        jScrollPane1.setViewportView(fdaSinopsis);

        lblStatus.setText("Sudah tonton?");

        rbSudah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbSudah.setForeground(new java.awt.Color(0, 255, 0));
        rbSudah.setText("Sudah");
        rbSudah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbSudah.setPreferredSize(new java.awt.Dimension(60, 23));

        rbBelum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbBelum.setForeground(new java.awt.Color(255, 0, 0));
        rbBelum.setText("Belum");
        rbBelum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbGenre1.setModel(new DefaultComboBoxModel(DatabaseUtil.selectSemuaGenre().toArray()));
        cbGenre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenre1ActionPerformed(evt);
            }
        });

        cbGenre2.setModel(new DefaultComboBoxModel(DatabaseUtil.selectSemuaGenre().toArray()));
        cbGenre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenre2ActionPerformed(evt);
            }
        });

        cbGenre3.setModel(new DefaultComboBoxModel(DatabaseUtil.selectSemuaGenre().toArray()));
        cbGenre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenre3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("judul :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("genre :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("sinopsis:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("studio :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("sutradara:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("tahun release :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSudah, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblPeringkat)
                                .addGap(18, 18, 18)
                                .addComponent(spiPeringkat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblStatus))
                            .addComponent(btnPilihSampulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCover, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fldSutradara, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fldJudul, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(cbGenre1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbGenre2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbGenre3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(423, 423, 423)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(11, 11, 11))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(10, 10, 10))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(fldStudio))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fldTahunrelease, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbBelum)
                                    .addComponent(btnTambah))
                                .addGap(119, 119, 119)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbGenre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGenre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGenre1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldSutradara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(fldStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblCover, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(fldTahunrelease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnPilihSampulBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatus)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPeringkat)
                                    .addComponent(spiPeringkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbSudah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbBelum)))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnBatal))
                .addGap(39, 39, 39))
        );

        BufferedImage cover = null;
        try{
            cover = ImageIO.read(new File("images/buku/defaultImage.jpg"));
            BufferedImage scaledCover = Scalr.resize(cover,147);

            ImageIcon coverIcon = new ImageIcon(scaledCover);
            lblCover.setIcon(coverIcon);
        }
        catch(IOException e){
            System.out.println(e.getMessage());
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private final ButtonGroup grpStatus = new ButtonGroup();
    ArrayList<String> itemSelects = new ArrayList<>();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnTambah.requestFocus();
        this.getRootPane().setDefaultButton(btnTambah);
        new PlaceHolder(fldJudul,"Judul");
        new PlaceHolder(fldSutradara,"Sutradara");
        new PlaceHolder(fldStudio,"studio");
        new PlaceHolder(fldTahunrelease,"Tahun release");
        new PlaceHolder(fdaSinopsis,"Sinopsis . . .");
        
        //grouping rb
        grpStatus.add(rbBelum);

        grpStatus.add(rbSudah);
        
        rbBelum.setSelected(true);

        //Listing cbGenre
        cbGenres.add(cbGenre1);
        cbGenres.add(cbGenre2);
        cbGenres.add(cbGenre3);
        
        for(JComboBox cbGenre : cbGenres){
            cbGenre.addItem("Genre");
            cbGenre.setSelectedItem("Genre");
        }
        for(JComboBox cbGenreTemp2: cbGenres){
            itemSelects.add((String) cbGenreTemp2.getSelectedItem());
        }
        int i = 0;
    }//GEN-LAST:event_formWindowOpened

    private File fileCover = null;
    private String pathSampul = "";
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String judul = fldJudul.getText();
        String sutradara = fldSutradara.getText();
        String studio = fldStudio.getText();
        int peringkat = (int) spiPeringkat.getValue();
        String sinopsis = fdaSinopsis.getText();
        String status;
        if(rbSudah.isSelected()) status = "2";
        
        else status = "0";
        
        if(fileCover != null){
            String fileName = fldJudul.getText() + "-" +
                    fldSutradara.getText() + "." +
                    ExtensionUtil.getExtension(fileCover);
            Path target = Paths.get("images/movie/" + fileName);
            try {
                Files.copy(fileCover.toPath(), target, StandardCopyOption.REPLACE_EXISTING);
                
                pathSampul = fileName;
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }
        
        ArrayList<String> genres = new ArrayList<>();
        for(JComboBox cbGenre: cbGenres){
            if(!cbGenre.getSelectedItem().equals("Genre") && 
                    !genres.contains((String) cbGenre.getSelectedItem())){
                genres.add((String) cbGenre.getSelectedItem());
            }
        }
        int tahunrelease = 0;
        boolean isSuccess = false;
        
        try{
            if(!"Tahun release".equals(fldTahunrelease.getText())) tahunrelease = 
                    Integer.parseInt(fldTahunrelease.getText());
            
            if(!judul.equals("Judul") && !sutradara.equals("Sutradara")){
                isSuccess = DatabaseUtil.createMovie(judul, sutradara, studio, genres, peringkat, 
                    tahunrelease, sinopsis, status, pathSampul);
            
                if(isSuccess){
                    JOptionPane.showMessageDialog(this, 
                                        "Movie berhasil ditambahkan",
                                        "Movie Ditambahkan",
                                        JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
                else{
                    
                    JOptionPane.showMessageDialog(this,
                                        "Movie gagal ditambahkan",
                                        "Error: Movie Gagal Ditambahkan",
                                        JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                
                JOptionPane.showMessageDialog(this,
                        "Judul dan Sutradara tidak boleh kosong atau diisi \"Judul\"  dan \"Sutradara\"",
                        "Error: Judul dan Sutradara Kosong",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException | HeadlessException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnPilihSampulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihSampulBukuActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.addChoosableFileFilter(new ImageFilter());
        jfc.setAcceptAllFileFilterUsed(false);
        
        int returnVal = jfc.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            
            try {
                BufferedImage image = ImageIO.read(file);
                
                BufferedImage scaledImage = Scalr.resize(image,147);
                ImageIcon coverIcon = new ImageIcon (scaledImage);
                lblCover.setIcon(coverIcon);
                
                fileCover = file;
                pathSampul = file.getAbsolutePath();
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        } else {
        }
    }//GEN-LAST:event_btnPilihSampulBukuActionPerformed

    private void cbGenre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenre1ActionPerformed

    private void cbGenre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenre2ActionPerformed

    private void fldJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldJudulActionPerformed

    private void cbGenre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenre3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgTambahMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgTambahMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgTambahMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgTambahMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgTambahMovie dialog = new dlgTambahMovie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnPilihSampulBuku;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbGenre1;
    private javax.swing.JComboBox<String> cbGenre2;
    private javax.swing.JComboBox<String> cbGenre3;
    private javax.swing.JTextArea fdaSinopsis;
    private javax.swing.JTextField fldJudul;
    private javax.swing.JTextField fldStudio;
    private javax.swing.JTextField fldSutradara;
    private javax.swing.JTextField fldTahunrelease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCover;
    private javax.swing.JLabel lblPeringkat;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton rbBelum;
    private javax.swing.JRadioButton rbSudah;
    private javax.swing.JSpinner spiPeringkat;
    // End of variables declaration//GEN-END:variables
}
