/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movie_database;
/**
 *
 * @author Fabrian
 */

import com.placeholder.PlaceHolder;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.border.Border;



public class Mainpage extends javax.swing.JFrame {
//    public String password = "admin";
   // public boolean isLogin = false;
    public static final String NEWLINE = "\n";
    private JPanel pnlSemuaMovie = new JPanel();
    /**
     * Creates new form Home
     */
    public Mainpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator1 = new javax.swing.JSeparator();
        btnTambahMovie = new javax.swing.JButton();
        tabMovie = new javax.swing.JTabbedPane();
        pnlTemp = new javax.swing.JPanel();
        btnTambahGenre = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnHapusGenre = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(372, 154));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnTambahMovie.setText("Tambah Movie");
        btnTambahMovie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTempLayout = new javax.swing.GroupLayout(pnlTemp);
        pnlTemp.setLayout(pnlTempLayout);
        pnlTempLayout.setHorizontalGroup(
            pnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        pnlTempLayout.setVerticalGroup(
            pnlTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        tabMovie.addTab("tab1", pnlTemp);

        btnTambahGenre.setText("+");
        btnTambahGenre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahGenreActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnHapusGenre.setText("-");
        btnHapusGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusGenreActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabMovie)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambahMovie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambahGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusGenre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahMovie)
                    .addComponent(btnTambahGenre)
                    .addComponent(btnHapusGenre)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabMovie)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
     private void tampilSemuaDataMovie(){
        tabMovie.removeAll();
        
        pnlSemuaMovie.removeAll();
        ArrayList<Movie> movies = DatabaseUtil.selectSemuaMovie();
        
        GridBagLayout gblPanelAll = new GridBagLayout();
        GridBagConstraints gbcPanelAll = new GridBagConstraints();
        
        pnlSemuaMovie.setLayout(gblPanelAll);
        
        int x = 0,y = 0;
        int width = 300; 
        int height = 250;
        
        for(Movie movie : movies){
            JPanel panel = new JPanel();
            GridBagLayout gblPanel = new GridBagLayout();
            GridBagConstraints gbcPanel = new GridBagConstraints();
            panel.setLayout(gblPanel);
            panel.setMinimumSize(new Dimension(width,height));
            panel.setPreferredSize(new Dimension(width,height));
            panel.setVisible(true);
            
           if(movie.getStatus()=="2"){
            panel.setBackground(Color.GREEN);
          }else if(movie.getStatus()=="0"){
            panel.setBackground(Color.YELLOW);
                  }
        
            //gambar
            gbcPanel.fill = GridBagConstraints.NONE;
            gbcPanel.weightx = 1;
            gbcPanel.weighty = 10;
            gbcPanel.gridwidth = 1;
            gbcPanel.gridheight = 10;
            gbcPanel.gridx = 0;
            gbcPanel.gridy = 0;
            JLabel lblCover = new JLabel();
            panel.add(lblCover,gbcPanel);
            BufferedImage coverImage;
            try{
                coverImage = ImageIO.read(new File("images/movie/" + movie.getPathSampul()));
                BufferedImage scaledCoverImage = Scalr.resize(coverImage,205);

                ImageIcon coverIcon = new ImageIcon(scaledCoverImage);
                lblCover.setIcon(coverIcon);
            }
            catch(IOException e){
            }
            
            int xKanan = 1;
            Font fDataMovie = new Font(Font.SANS_SERIF,Font.PLAIN,12);
            Font fJudulMovie = new Font(Font.SANS_SERIF,Font.BOLD,18);
            
            
            gbcPanel.insets = new Insets(3,3,3,3);
            

            //judul            
            gbcPanel.fill = GridBagConstraints.BOTH;
            gbcPanel.weightx = 8;
            gbcPanel.weighty = 1;
            gbcPanel.gridwidth = 7;
            gbcPanel.gridheight = 1;
            gbcPanel.gridx = 1;
            gbcPanel.gridy = 0;
            JLabel lblJudul = new JLabel();
            lblJudul.setFont(fJudulMovie);
            lblJudul.setText(movie.getJudul());
            panel.add(lblJudul,gbcPanel);
            
            //iconX
            gbcPanel.fill = GridBagConstraints.BOTH;
            gbcPanel.weightx = 0.1;
            gbcPanel.weighty = 1;
            gbcPanel.gridwidth = xKanan;
            gbcPanel.gridheight = 1;
            gbcPanel.gridx = 2;
            gbcPanel.gridy = 0;
            
            JLabel lbliconX = new JLabel(new ImageIcon("images/icon/iconx_nonhover.png"));
            String judul = movie.getJudul();
            String sutradara = movie.getSutradara();
            lbliconX.setCursor(new Cursor(Cursor.HAND_CURSOR));
            
            
            lbliconX.addMouseListener(new MouseListener(){
                @Override
                public void mouseClicked(MouseEvent me) {
                   
                        int answer = JOptionPane.showConfirmDialog(null,
                                "Apakah anda yakin?",
                                "Hapus Movie",
                                JOptionPane.YES_NO_OPTION);

                        if(answer == JOptionPane.YES_OPTION){
                            boolean isSuccess = DatabaseUtil.deleteMovie(movie.getJudul(), 
                                    movie.getSutradara());

                            if(isSuccess){
                                JOptionPane.showMessageDialog(null,
                                        "Movie " + judul + " oleh " + sutradara 
                                                +" telah berhasil dihapus.",
                                        "Delete Berhasil",
                                        JOptionPane.INFORMATION_MESSAGE);
                                tampilSemuaDataMovie();
                            }
                            else{
                              
                                JOptionPane.showMessageDialog(null,
                                        "Terjadi kesalahan sistem, movie gagal dihapus.",
                                        "Error: Delete Gagal",
                                        JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    
                    
                }

                @Override
                public void mousePressed(MouseEvent me) {
                     //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void mouseReleased(MouseEvent me) {
                   //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void mouseEntered(MouseEvent me) {
                    //To change body of generated methods, choose Tools | Templates.
                    
                    lbliconX.setIcon(new ImageIcon ("images/icon/iconx_hover.png"));
                            
                }

                @Override
                public void mouseExited(MouseEvent me) {
                    lbliconX.setIcon(new ImageIcon ("images/icon/iconX_nonhover.png"));
                    //To change body of generated methods, choose Tools | Templates.
                }
            });
            panel.add(lbliconX,gbcPanel);
            
            //sutradara
            gbcPanel.fill = GridBagConstraints.BOTH;
            gbcPanel.weightx = xKanan;
            gbcPanel.weighty = 1;
            gbcPanel.gridwidth = 2;
            gbcPanel.gridheight = 1;
            gbcPanel.gridx = 1;
            gbcPanel.gridy = 1;
            JLabel lblsutradara = new JLabel();
            lblsutradara.setText("oleh "+movie.getSutradara());
            lblsutradara.setFont(fDataMovie);
            panel.add(lblsutradara,gbcPanel);
            
            //TahunTerbit
            gbcPanel.fill = GridBagConstraints.BOTH;
            gbcPanel.weightx = xKanan;
            gbcPanel.weighty = 1;
            gbcPanel.gridwidth = 2;
            gbcPanel.gridheight = 1;
            gbcPanel.gridx = 1;
            gbcPanel.gridy = 2;
            JLabel lblDataTahunrelease = new JLabel();
            lblDataTahunrelease.setText("Tahun " + Integer.toString(movie.getTahunrelease()));
            lblDataTahunrelease.setFont(fDataMovie);
            panel.add(lblDataTahunrelease,gbcPanel);
            
            //studio
            gbcPanel.fill = GridBagConstraints.BOTH;
            gbcPanel.weightx = xKanan;
            gbcPanel.weighty = 1;
            gbcPanel.gridwidth = 2;
            gbcPanel.gridheight = 1;
            gbcPanel.gridx = 1;
            gbcPanel.gridy = 3;
            JLabel lblStudio = new JLabel();
            lblStudio.setText("di Garap oleh " + movie.getStudio());
            lblStudio.setFont(fDataMovie);
            panel.add(lblStudio,gbcPanel);
            
            //Peringkat
            gbcPanel.fill = GridBagConstraints.BOTH;
            gbcPanel.weightx = xKanan;
            gbcPanel.weighty = 1;
            gbcPanel.gridwidth = 2;
            gbcPanel.gridheight = 1;
            gbcPanel.gridx = 1;
            gbcPanel.gridy = 4;
            JLabel lblDataPeringkat = new JLabel();
            lblDataPeringkat.setText("Peringkat : "+ Integer.toString(movie.getPeringkat()) + " dari 10");
            lblDataPeringkat.setFont(fDataMovie);
            panel.add(lblDataPeringkat,gbcPanel);
            
            //Sinopsis
            gbcPanel.fill = GridBagConstraints.BOTH;
            gbcPanel.weightx = xKanan;
            gbcPanel.weighty = 6;
            gbcPanel.gridwidth = 2;
            gbcPanel.gridheight = 3;
            gbcPanel.gridx = 1;
            gbcPanel.gridy = 5;
            JScrollPane jspFdaSinopsis = new JScrollPane();
            JTextArea fdaSinopsis = new JTextArea();
            fdaSinopsis.setText(movie.getSinopsis());
            fdaSinopsis.setLineWrap(true);
            fdaSinopsis.setWrapStyleWord(true);
            fdaSinopsis.setColumns(20);
            fdaSinopsis.setRows(5);
            fdaSinopsis.setFont(fDataMovie);
            fdaSinopsis.setEditable(false);
            jspFdaSinopsis.setViewportView(fdaSinopsis);
//            jspFdaSinopsis.add(fdaSinopsis);
            panel.add(jspFdaSinopsis,gbcPanel);
            
            //Status  
            gbcPanel.fill = GridBagConstraints.BOTH;
            gbcPanel.weightx = xKanan;
            gbcPanel.weighty = 1;
            gbcPanel.gridwidth = xKanan;
            gbcPanel.gridheight = 1;
            gbcPanel.gridx = 1;
            gbcPanel.gridy = 9;
            JLabel lblStatus = new JLabel();
            lblStatus.setText("Status tonton : " + movie.getTranslatedStatus() + " ditonton");
            lblStatus.setFont(fDataMovie);
            panel.add(lblStatus,gbcPanel);
            
            //genre
            gbcPanel.fill = GridBagConstraints.BOTH;
            gbcPanel.weightx = 3;
            gbcPanel.weighty = 1;
            gbcPanel.gridwidth = 3;
            gbcPanel.gridheight = 1;
            gbcPanel.gridx = 0;
            gbcPanel.gridy = 10;
            JLabel lblGenre = new JLabel();
            lblGenre.setText("Belum ada Genre");
            ArrayList<String> genres= new ArrayList<>();
            if(movie.getGenres().size()>0){
                genres= movie.getGenres();
                int i=0;
                for (String genre:genres){
                    if(i==0) lblGenre.setText(genre);
                    else lblGenre.setText(lblGenre.getText()+","+ genre);
                    i++;      
                }
                
            }
            lblGenre.setForeground(Color.BLUE);
            lblGenre.setFont(fDataMovie);
            lblGenre.setHorizontalAlignment(SwingConstants.CENTER);
            panel.add(lblGenre,gbcPanel);
            

            //membuat klik kanan pada panel
            JPopupMenu popPanel;
            
            popPanel = new JPopupMenu();
            JMenuItem miEdit = new JMenuItem("Edit movie");
            miEdit.addActionListener((ActionEvent ae) -> {
                
                    dlgEditMovie deb = new dlgEditMovie(this, true);
                    deb.setJudul(judul);
                    deb.setSutradara(sutradara);
                    deb.setLocationRelativeTo(null);
                    deb.setVisible(true);

                    tampilSemuaDataMovie();
                
                
            });
            popPanel.add(miEdit);
            
            popPanel.addSeparator();
            
            JMenuItem miDelete = new JMenuItem("Delete movie");
            miDelete.addActionListener((ActionEvent ae) -> {
                
                    int answer = JOptionPane.showConfirmDialog(null,
                            "Apakah anda yakin?",
                            "Hapus Movie",
                            JOptionPane.YES_NO_OPTION);

                    if(answer == JOptionPane.YES_OPTION){
                        boolean isSuccess = DatabaseUtil.deleteMovie(movie.getJudul(), 
                                movie.getSutradara());

                        if(isSuccess){
                            JOptionPane.showMessageDialog(null,
                                    "Movie " + judul + " oleh " + sutradara 
                                            +" telah berhasil dihapus.",
                                    "Delete Berhasil",
                                    JOptionPane.INFORMATION_MESSAGE);
                            tampilSemuaDataMovie();
                        }
                        else{
                            
                            JOptionPane.showMessageDialog(null,
                                    "Terjadi kesalahan sistem, movie gagal dihapus.",
                                    "Error: Delete Gagal",
                                    JOptionPane.ERROR_MESSAGE);
                        }
                    }
                
               
            });
            popPanel.add(miDelete);

            //Add listener to components that can bring up popup menus.
            panel.setComponentPopupMenu(popPanel);
            fdaSinopsis.setComponentPopupMenu(popPanel);
            jspFdaSinopsis.setComponentPopupMenu(popPanel);
            
            //panel
            gbcPanelAll.insets = new Insets(5,5,5,5);
            gbcPanelAll.fill = GridBagConstraints.HORIZONTAL;
            gbcPanelAll.weightx = xKanan;
            gbcPanelAll.weighty = 1;
            gbcPanelAll.gridx = x;
            gbcPanelAll.gridy = y;
            
            pnlSemuaMovie.add(panel,gbcPanelAll);
            
            
            x++;
            if(x == 3){
                x = 0;
                y++;
            }
        }
        
        if(movies.size() < 6){
            JPanel panelKosong = new JPanel();
            panelKosong.setMinimumSize(new Dimension(width,height));
            panelKosong.setPreferredSize(new Dimension(width,height));
            panelKosong.setVisible(true);
            
            int count = movies.size();
            while(count < 6){
                gbcPanelAll.fill = GridBagConstraints.HORIZONTAL;
                gbcPanelAll.weightx = 1;
                gbcPanelAll.weighty = 1;
                gbcPanelAll.gridx = x;
                gbcPanelAll.gridy = y;
                
                pnlSemuaMovie.add(panelKosong,gbcPanelAll);
                count++;
                x++;
                if(x == 3){
                    x = 0;
                    y++;
                }
            }
            
        }
        tabMovie.add(new JScrollPane(pnlSemuaMovie),BorderLayout.CENTER);
        tabMovie.setTitleAt(0,"All");
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnTambahMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMovieActionPerformed
        // TODO add your handling code here:
       
           dlgTambahMovie dtb = new dlgTambahMovie(this,true);
           dtb.setLocationRelativeTo(null);
            dtb.setVisible(true);
            
           tampilSemuaDataMovie();
        
       
    }//GEN-LAST:event_btnTambahMovieActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        this.setFocusCycleRoot(true);
    }//GEN-LAST:event_formMouseClicked

    char switchBtnLoginFunction = 'a';
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        

     
       // new PlaceHolder(fldSearch,"Search here...");
      
        
       tampilSemuaDataMovie();
    }//GEN-LAST:event_formWindowOpened

    char switchBtnFilterFunction = 'a';
    private void btnTambahGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahGenreActionPerformed
        
            dlgTambahGenre dtg = new dlgTambahGenre(this,true);
            dtg.setVisible(true);
            dtg.setLocationRelativeTo(this);
        
       
    }//GEN-LAST:event_btnTambahGenreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Search().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHapusGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusGenreActionPerformed
        // TODO add your handling code here:
         dlghapusGenre dhg = new dlghapusGenre(this,true);
            dhg.setVisible(true);
            dhg.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnHapusGenreActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        login l = new login();
        Mainpage.this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainpage().setVisible(true);
            }
        });
         
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusGenre;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTambahGenre;
    private javax.swing.JButton btnTambahMovie;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel pnlTemp;
    private javax.swing.JSeparator separator1;
    private javax.swing.JTabbedPane tabMovie;
    // End of variables declaration//GEN-END:variables
}
