/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.database;

import com.placeholder.PlaceHolder;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Fabrian
 */
public class DialAddMovie extends javax.swing.JDialog {

     private ArrayList<JComboBox> cbGenres = new ArrayList<>();
    /**
     * Creates new form DialAddMovie
     */
    public DialAddMovie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fldJudul = new javax.swing.JTextField();
        cbGenre1 = new javax.swing.JComboBox<>();
        cbGenre2 = new javax.swing.JComboBox<>();
        cbGenre3 = new javax.swing.JComboBox<>();
        fldSutradara = new javax.swing.JTextField();
        fldReleasedate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fdaSinopsis = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCover = new javax.swing.JLabel();
        btncoverfilm = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fldJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldJudulActionPerformed(evt);
            }
        });

        cbGenre1.setModel(new DefaultComboBoxModel(DatabaseUtil.selectSemuaGenre().toArray()));
        cbGenre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenre1ActionPerformed(evt);
            }
        });

        cbGenre2.setModel(new DefaultComboBoxModel(DatabaseUtil.selectSemuaGenre().toArray()));
        cbGenre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenre2ActionPerformed(evt);
            }
        });

        cbGenre3.setModel(new DefaultComboBoxModel(DatabaseUtil.selectSemuaGenre().toArray()));

        fldSutradara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSutradaraActionPerformed(evt);
            }
        });

        fdaSinopsis.setColumns(20);
        fdaSinopsis.setLineWrap(true);
        fdaSinopsis.setRows(5);
        fdaSinopsis.setWrapStyleWord(true);
        jScrollPane1.setViewportView(fdaSinopsis);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add Movie");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Judul :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Genre :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Sinopsis :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Sutradara :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tahun release : ");

        lblCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCover.setName(""); // NOI18N

        btncoverfilm.setText("Pilih Sampul Buku");
        btncoverfilm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncoverfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoverfilmActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbGenre1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbGenre2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbGenre3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fldSutradara, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fldReleasedate, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btncoverfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(btnTambah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGenre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGenre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGenre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fldSutradara, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fldReleasedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnBatal))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCover, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btncoverfilm)
                .addGap(84, 84, 84))
        );

        BufferedImage cover = null;
        try{
            cover = ImageIO.read(new File("images/buku/defaultImage.jpg"));
            BufferedImage scaledCover = Scalr.resize(cover,147);

            ImageIcon coverIcon = new ImageIcon(scaledCover);
            lblCover.setIcon(coverIcon);
        }
        catch(IOException e){
            System.out.println(e.getMessage());
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private final ButtonGroup grpStatus = new ButtonGroup();
  ArrayList<String> itemSelects = new ArrayList<>();
      private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        btnTambah.requestFocus();
        this.getRootPane().setDefaultButton(btnTambah);
        new PlaceHolder(fldJudul,"Judul");
        new PlaceHolder(fldSutradara,"Pengarang");
        new PlaceHolder(fldReleasedate,"Tahun Terbit");
        new PlaceHolder(fdaSinopsis,"Sinopsis . . .");
        
       
        //Listing cbGenre
        cbGenres.add(cbGenre1);
        cbGenres.add(cbGenre2);
        cbGenres.add(cbGenre3);
        
        for(JComboBox cbGenre : cbGenres){
            cbGenre.addItem("Genre");
            cbGenre.setSelectedItem("Genre");
        }
        for(JComboBox cbGenreTemp2: cbGenres){
            itemSelects.add((String) cbGenreTemp2.getSelectedItem());
        }
        int i = 0;
    }                                 
    private File fileCover = null;
    private String pathSampul = "";
    private void fldJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldJudulActionPerformed

    private void cbGenre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenre1ActionPerformed

    private void cbGenre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenre2ActionPerformed

    private void fldSutradaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSutradaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSutradaraActionPerformed

    private void btncoverfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoverfilmActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.addChoosableFileFilter(new ImageFilter());
        jfc.setAcceptAllFileFilterUsed(false);

        int returnVal = jfc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();

            try {
                BufferedImage image = ImageIO.read(file);

                BufferedImage scaledImage = Scalr.resize(image,147);
                ImageIcon coverIcon = new ImageIcon (scaledImage);
                lblCover.setIcon(coverIcon);

                fileCover = file;
                pathSampul = file.getAbsolutePath();
                } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        } else {
        }
    }//GEN-LAST:event_btncoverfilmActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String judul = fldJudul.getText();
        String sutradara = fldSutradara.getText();
        String sinopsis = fdaSinopsis.getText();
        //int releasedate = fldReleasedate.getText();
        
        if(fileCover != null){
            String fileName = fldJudul.getText() + "-" +
            fldSutradara.getText() + "." +
            ExtensionUtil.getExtension(fileCover);
            Path target = Paths.get("images/movie/" + fileName);
            try {
                Files.copy(fileCover.toPath(), target, StandardCopyOption.REPLACE_EXISTING);

                pathSampul = fileName;
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }

        ArrayList<String> genres = new ArrayList<>();
        for(JComboBox cbGenre: cbGenres){
            if(!cbGenre.getSelectedItem().equals("Genre") &&
                !genres.contains((String) cbGenre.getSelectedItem())){
                genres.add((String) cbGenre.getSelectedItem());
            }
        }
        int releasedate = 0;
        boolean isSuccess = false;

        try{
            if(!"Tahun Release".equals(fldReleasedate.getText())) releasedate =
            Integer.parseInt(fldReleasedate.getText());

            if(!judul.equals("Judul") && !sutradara.equals("Pengarang")){
                isSuccess = connect.createMovie(judul, sutradara, genres,
                    releasedate, sinopsis, pathSampul);

                if(isSuccess){
                    JOptionPane.showMessageDialog(this,
                        "Movie berhasil ditambahkan",
                        "Movie Ditambahkan",
                        JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
                else{
                    
                    JOptionPane.showMessageDialog(this,
                        "Movie gagal ditambahkan",
                        "Error: Movie Gagal Ditambahkan",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
               
                JOptionPane.showMessageDialog(this,
                    "Judul dan Sutradara tidak boleh kosong atau diisi \"Judul\"  dan \"Sutradara\"",
                    "Error: Judul dan Sutradara Kosong",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException | HeadlessException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialAddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialAddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialAddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialAddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialAddMovie dialog = new DialAddMovie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btncoverfilm;
    private javax.swing.JComboBox<String> cbGenre1;
    private javax.swing.JComboBox<String> cbGenre2;
    private javax.swing.JComboBox<String> cbGenre3;
    private javax.swing.JTextArea fdaSinopsis;
    private javax.swing.JTextField fldJudul;
    private javax.swing.JTextField fldReleasedate;
    private javax.swing.JTextField fldSutradara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCover;
    // End of variables declaration//GEN-END:variables
}
